<?php

$plugin_cf['miniblog']['archive_archiving_date']="";
$plugin_cf['miniblog']['archive_show_archive_button']="";
$plugin_cf['miniblog']['archive_archive_headline_style']="p";
$plugin_cf['miniblog']['posts_from_pages']="true";
$plugin_cf['miniblog']['posts_from_single_files']="true";
$plugin_cf['miniblog']['posts_from_members']="true";
$plugin_cf['miniblog']['posts_authorised_members']="";
$plugin_cf['miniblog']['backlinks_also_below_content']="true";
$plugin_cf['miniblog']['comments_plugin']="";
$plugin_cf['miniblog']['comments_default_on']="true";
$plugin_cf['miniblog']['blogpage_order_posts']="newest";
$plugin_cf['miniblog']['blogpage_limit_nr_of_posts_per_page']="";
$plugin_cf['miniblog']['blogpage_2_columns']="";
$plugin_cf['miniblog']['teaser_headline_style']="h1";
$plugin_cf['miniblog']['teaser_headline_is_link']="true";
$plugin_cf['miniblog']['teaser_img_path_for_members']="";
$plugin_cf['miniblog']['teaser_img_position']="teaser";
$plugin_cf['miniblog']['teaser_2nd_source']="<p";
$plugin_cf['miniblog']['teaser_generated_length']="250";
$plugin_cf['miniblog']['category_show_category_in_teaser']="true";
$plugin_cf['miniblog']['category_category_selection_buttons']="true";
$plugin_cf['miniblog']['category_enable_multicategory']="";
$plugin_cf['miniblog']['category_from_pagenames_with']="";
$plugin_cf['miniblog']['date_show_date']="true";
$plugin_cf['miniblog']['date_format']="d.m.Y";
$plugin_cf['miniblog']['keyword_show_keyword']="true";
$plugin_cf['miniblog']['keyword_2nd_source']="<h6";

?>
